### ISSUE TITLE
submodule support ? 

### ISSUE THREAD

**Issue by Milerius** [Semmle/lgtm-issue-tracker-example#6]
Hello after adding a submodule to my public repository i got this error:

```
[2019-04-05 21:57:25] [DEBUG] Running command: 'git --git-dir=/work/working/private/src/.git fetch --no-tags --recurse-submodules=no --prune -- /work/working/private/incremental_bundles/incremental.bundle +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/semmle/*:refs/semmle/*' in current directory ('/work/working/private') From /work/working/private/incremental_bundles/incremental.bundle * [new ref] refs/semmle/semmle-polled-revision-0fb74fb7647f3a876dba572bca803a5b6537c6e1 -> refs/semmle/semmle-polled-revision-0fb74fb7647f3a876dba572bca803a5b6537c6e1 [2019-04-05 21:57:26] [DEBUG] Stack trace: com.semmle.util.exception.UserError: Could not open git repository at /work/working/private/src/.git/modules/vendor/strong_type
```

my config:
```yml
extraction:
  cpp:
    prepare:    # Customizable step used by all languages.
      packages:
        - python-pip
        - pkg-config
    after_prepare:    # Customizable step used by all languages.
      - git submodule -q update --init
      - pip3 install --local cmake conan
      - pip3 install --local cmake conan --upgrade
      - ls ~/.local/bin
      - export PATH=$PATH:~/.local/bin
      - conan --version
      - cmake --version
      - conan profile new default --detect
      - conan profile update settings.compiler.version=8 default
      - conan profile update settings.compiler.libcxx=libstdc++11 default
      - conan remote update conan-center https://conan.bintray.com False
      - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan False
      - conan remote add skypjack https://api.bintray.com/conan/skypjack/conan False
      - mkdir $LGTM_SRC/_lgtm_build_dir
      - cd $LGTM_SRC/_lgtm_build_dir
      - conan install -g cmake ../
      - cd -
```

full log: 

https://lgtm.com/projects/g/Milerius/nephtys/logs/rev/pr-32ede09a4956bbe052eb655497a864a1db9b61c1/lang:cpp/stage:Build%20merge_0fb74fb7647f3a876dba572bca803a5b6537c6e1
